version: 0.0
os: linux
files:
  - source: /
    destination: /opt/wp-01
permissions:
  - object: /opt/wp-01
    owner: ubuntu
    group: ubuntu
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
#  ApplicationStop:
#    - location: scripts/stop_server.sh
#      timeout: 300
#      runas: ubuntu
